---
- name: Deploy Static Page
  hosts: all

  tasks:  
  - name: Creating a file with content
    copy:
      dest: "/var/www/html/index.html"
      content: |
        Welcome Everyone! {{ app_version }}
