---
- name: Create multiple local users
  hosts: all
  become: true
  vars_files:
    - vars/users_vars.yml

  tasks:
    - name: Add webadmin group
      ansible.builtin.group:
        name: webadmin
        state: present

    - name: Create user accounts
      ansible.builtin.user:
        name: "{{ item.username }}"
        groups: "{{ item.groups }}"
        state: present
      loop: "{{ users }}"

    - name: Assign password to users
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ item.password | password_hash('sha512') }}"
        state: present
      loop: "{{ users }}"
