- name: Create AWS VM
  hosts: localhost
  connection: local
  gather_facts: False

  collections:
    - amazon.aws

  - name: Create an EC2 instance
    ec2_instance:
      key_name: keypair_demo
      region: "{{ aws_region }}"
      security_group: "{{ firewall.group_id }}"
      instance_type: "t2.micro"
      image_id: "{{ ami_id }}"
      vpc_subnet_id: "{{ my_subnet.subnet.id }}"
      name: vm-demo
      network:
        assign_public_ip: true
    register: ec2
